services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  smartshopapi:
    image: robertf888/smartshopapi:latest
    ports:
      - "5888:8080"
    env_file:
      - .env
    environment:
      - RabbitMQ__Host=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__SmartShopDbConnection=Server=sqlserver;Database=SmartShopDB;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      - rabbitmq

  smartshopui:
    image: robertf888/smartshopui:latest
    ports:
      - "4288:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
