name: .NET CI

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "refactor/**"
      - "ci/**"
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore
      - run: dotnet build --no-restore

      - name: Run tests with coverage
        run: dotnet test --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate HTML coverage report
        run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Html

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport