name: Docker CD (API + UI)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push SmartShopAPI image
        uses: docker/build-push-action@v5
        with:
          context: ./SmartShopAPI/SmartShopAPI
          dockerfile: Dockerfile
          push: true
          tags: robertf888/smartshopapi:latest

      - name: Build and push SmartShopUI image
        uses: docker/build-push-action@v5
        with:
          context: ./SmartShopUI/SmartShopUI
          dockerfile: Dockerfile
          push: true
          tags: robertf888/smartshopui:latest
